// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from './deno.json' assert { type: 'json' }
import * as $0 from './routes/_middleware.ts'
import * as $1 from './routes/account.tsx'
import * as $2 from './routes/api/claim.ts'
import * as $3 from './routes/api/claims/handle.ts'
import * as $4 from './routes/api/db/claims.ts'
import * as $5 from './routes/api/db/codes.ts'
import * as $6 from './routes/api/db/outings.ts'
import * as $7 from './routes/api/db/users.ts'
import * as $8 from './routes/api/login.ts'
import * as $9 from './routes/api/logout.ts'
import * as $10 from './routes/api/outings/add.ts'
import * as $11 from './routes/api/outings/delete.ts'
import * as $12 from './routes/api/outings/edit.ts'
import * as $13 from './routes/code/[code].tsx'
import * as $14 from './routes/index.tsx'
import * as $15 from './routes/info.tsx'
import * as $16 from './routes/invite.tsx'
import * as $$0 from './islands/ActionButton.tsx'
import * as $$1 from './islands/AddSessionDialogButton.tsx'
import * as $$2 from './islands/ClaimDialogButton.tsx'
import * as $$3 from './islands/Copyable.tsx'
import * as $$4 from './islands/DialogSubmitter.tsx'
import * as $$5 from './islands/EditSessionDialogButton.tsx'
import * as $$6 from './islands/InstallPwaButton.tsx'
import * as $$7 from './islands/InviteCodeButton.tsx'
import * as $$8 from './islands/LogoutButton.tsx'
import * as $$9 from './islands/NotifiedButton.tsx'
import * as $$10 from './islands/OutingsGallery.tsx'
import * as $$11 from './islands/Redirect.tsx'
import * as $$12 from './islands/ShareButton.tsx'
import * as $$13 from './islands/Submitter.tsx'
import * as $$14 from './islands/Toast.tsx'

const manifest = {
	routes: {
		'./routes/_middleware.ts': $0,
		'./routes/account.tsx': $1,
		'./routes/api/claim.ts': $2,
		'./routes/api/claims/handle.ts': $3,
		'./routes/api/db/claims.ts': $4,
		'./routes/api/db/codes.ts': $5,
		'./routes/api/db/outings.ts': $6,
		'./routes/api/db/users.ts': $7,
		'./routes/api/login.ts': $8,
		'./routes/api/logout.ts': $9,
		'./routes/api/outings/add.ts': $10,
		'./routes/api/outings/delete.ts': $11,
		'./routes/api/outings/edit.ts': $12,
		'./routes/code/[code].tsx': $13,
		'./routes/index.tsx': $14,
		'./routes/info.tsx': $15,
		'./routes/invite.tsx': $16,
	},
	islands: {
		'./islands/ActionButton.tsx': $$0,
		'./islands/AddSessionDialogButton.tsx': $$1,
		'./islands/ClaimDialogButton.tsx': $$2,
		'./islands/Copyable.tsx': $$3,
		'./islands/DialogSubmitter.tsx': $$4,
		'./islands/EditSessionDialogButton.tsx': $$5,
		'./islands/InstallPwaButton.tsx': $$6,
		'./islands/InviteCodeButton.tsx': $$7,
		'./islands/LogoutButton.tsx': $$8,
		'./islands/NotifiedButton.tsx': $$9,
		'./islands/OutingsGallery.tsx': $$10,
		'./islands/Redirect.tsx': $$11,
		'./islands/ShareButton.tsx': $$12,
		'./islands/Submitter.tsx': $$13,
		'./islands/Toast.tsx': $$14,
	},
	baseUrl: import.meta.url,
	config,
}

export default manifest
